In [31]:
import numpy as np
grid = [[5,3,0,0,7,0,0,0,0],
       [6,0,0,1,9,5,0,0,0],
       [0,9,8,0,0,0,0,6,0],
       [8,0,0,0,6,0,0,0,3],
       [4,0,0,8,0,3,0,0,1],
       [7,0,0,0,2,0,0,0,6],
       [0,6,0,0,0,0,2,8,0],
       [0,0,0,4,1,9,0,0,5],
       [0,0,0,0,8,0,0,7,9]]
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 9 0 0 7 9]]


In [32]:
def checkValidSudoku():
    global grid
    for i in range(9):
        for j in range(9):
            val = grid[i][j]
            if val > 0:
                for col in range(9):
                    if col != j and grid[i][col] == val:
                        return False
                for row in range(9):
                    if row != i and grid[row][j] == val:
                        return False
                row0 = (i//3)*3
                col0 = (j//3)*3
                for r in range(3):
                    for c in range(3):
                        if grid[row0+r][col0+c] == val:
                            if row0+r != i and col0+c != j:
                                return False
    return True

In [33]:
print(checkValidSudoku())

False


In [2]:
def isPossible(row,col,num):
    global grid
    for i in range(9):
#         row-wise checking
        if grid[row][i] == num:
            return False
    for i in range(9):
#         column-wise checking
        if grid[i][col] == num:
            return False
    col0 = (col//3)*3
    row0 = (row//3)*3
    for i in range(3):
        for j in range(3):
#             small-grid-wise checking
            if grid[row0+i][col0+j] == num:
                return False
    return True
            

In [3]:
print(possible(4,4,3))

False


In [ ]:
print(validSudoku())

In [4]:
def solve():
    global grid
    for row in range(9):
        for col in range(9):
            if grid[row][col] == 0:
                for n in range(1,10):
                    if isPossible(row, col, n):
                        grid[row][col] = n
                        solve()
                        grid[row][col] = 0
                return
    print(np.matrix(grid))
    

In [6]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
